### PR TITLE
rpcdaemon: fix eth_call without sender

### LINKED ISSUE #2017: rpcdaemon: `eth_call` returns error when (optional) sender parameter is absent
When trying to query a smart contract, such as like this:

```json
{
	"id": 19,
	"jsonrpc": "2.0",
	"method": "eth_call",
	"params": [
		{
			"data": "0xfeaf968c",
			"to": "0xffe5b13cb108a99edf87926faf09d5008186dd91"
		},
		"latest"
	]
}
```

Erigon replies with an error saying the sender cannot be recovered:
```json
{
	"jsonrpc": "2.0",
	"id": 19,
	"error": {
		"code": -32000,
		"message": "malformed transaction: cannot recover sender"
	}
}
```

Note that by default, if a sender isn't given it's assumed to be the zero address.

### PR DESCRIPTION
**Pull request by lupin012**
If sender is not specified in `Call` parameter of `eth_call`, zero address should be used.

Fixes #2017

### CODE REVIEW

File: silkworm/rpc/core/evm_executor.cpp [hunk 1]
```diff
@@ -238,9 +238,6 @@ ExecutionResult EVMExecutor::call(
         evm.add_tracer(*tracer);
     }
 
-    if (!txn.sender()) {
-        return {std::nullopt, txn.gas_limit, Bytes{}, "malformed transaction: cannot recover sender"};
-    }
```
Comment (canepat) [inline silkworm/rpc/core/evm_executor.cpp:243]: I would prefer not to remove this check because at the `EVMExecutor` API level it still makes a lot of sense.

File: silkworm/rpc/types/call.hpp [hunk 2]
```diff
@@ -51,6 +51,9 @@ struct Call {
         silkworm::Transaction txn{};
         if (from) {
             txn.set_sender(*from);
+        } else {
+            constexpr auto zero_address = 0x0000000000000000000000000000000000000000_address;
+            txn.set_sender(zero_address);
         }
```
Comment (canepat) [inline silkworm/rpc/types/call.hpp:57]: Now you can and should simplify this by removing the `if-else` clause:
```
txn.set_sender(from ? *from : evmc::address{});
```

**Review by canepat — CHANGES_REQUESTED** [review]

File: silkworm/rpc/types/call.hpp (hunk 2 above)
Comment (lupin012) [reply silkworm/rpc/types/call.hpp:57]: ok

File: silkworm/rpc/core/evm_executor.cpp (hunk 1 above)
Comment (lupin012) [reply silkworm/rpc/core/evm_executor.cpp:243]: ok

**Review by canepat — APPROVED** [review]
