### PR TITLE
sentry: fix unhandled exception in peer handshake close

### LINKED ISSUE #1896: sentry: unhandled exception when closing peer during termination
```
...
  INFO [03-08|21:52:47.143 UTC] sync::SentryClient                       Peer fca3cd08796058cb0e2eabf559084ac45c241cdf connected, active 7, info: -info-not-found-
  INFO [03-08|21:52:47.220 UTC] sync::SentryClient                       Peer fca3cd08796058cb0e2eabf559084ac45c241cdf disconnected, active 7, info: -info-not-found-
  INFO [03-08|21:53:03.030 UTC] sync::SentryClient                       Peer fea359e2843059d4f99bb09da45400a6b3f145e8 connected, active 7, info: -info-not-found-
  INFO [03-08|21:53:03.091 UTC] sync::SentryClient                       Peer fea359e2843059d4f99bb09da45400a6b3f145e8 disconnected, active 7, info: -info-not-found-
^C
  INFO [03-08|21:53:05.666 UTC] Signal caught, number: 2
  WARN [03-08|21:53:05.671 UTC] State changes stream read error [Cancelling all calls], schedule reopen
  WARN [03-08|21:53:05.721 UTC] State changes stream cancelled
  CRIT [03-08|21:53:06.772 UTC] Silkworm terminating due to exception: AwaitablePromise::set: channel is full
zsh: abort      cmake-build-clang-release/cmd/silkworm --datadir ~/Library/SilkwormSepolia  
```

This is caused by some `sentry::RLPx::Peer` instance during program termination.

### PR DESCRIPTION
**Pull request by canepat**
Fixes #1896

### CODE REVIEW

File: silkworm/sentry/rlpx/peer.cpp [hunk 1]
```diff
@@ -104,7 +104,11 @@ Task<void> Peer::handle() {
     bool is_handshake_completed = false;
     [[maybe_unused]] auto _ = gsl::finally([this, &is_handshake_completed] {
         if (!is_handshake_completed) {
-            this->handshake_promise_.set_value(false);
+            try {
+                this->handshake_promise_.set_value(false);
+            } catch (const std::exception& e) {
```
Comment (battlmonstr) [inline silkworm/sentry/rlpx/peer.cpp:109]: what kind of exception is thrown and why?
is it possible to avoid a "catch all" and "ignore" here?

**Review by battlmonstr — CHANGES_REQUESTED** [review]

**Review by battlmonstr — APPROVED** [review]

File: silkworm/sentry/rlpx/peer.cpp (hunk 1 above)
Comment (canepat) [reply silkworm/sentry/rlpx/peer.cpp:109]: It's a `std::runtime_error` we raise in `AwaitableFuture::set` when `AsyncChannel::try_send` returns false (i.e. not sent) and the channel is still open. We definitely can investigate this issue more and probably have a better fix, but I propose to do this in next PR on the subject.

Maybe we can to keep #1896 open and then you can put it on your todo list, if you agree
