### PR TITLE
infra: setup signal handling with SA_ONSTACK flag

### LINKED ISSUE #1940: C API execute blocks: non-Go code set up signal handler without SA_ONSTACK flag
If you launch Silkworm C API block execution on Linux from Go code and then hit CTRL-C, you may sometimes encounter the following unhandled exception:
```
signal 2 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag
```
This is because the Go runtime expects its signal handlers to be called on their dedicated signal stack, as stated in Go [documentation](https://pkg.go.dev/os/signal#hdr-Go_programs_that_use_cgo_or_SWIG):

> If the non-Go code installs any signal handlers, it must use the SA_ONSTACK flag with sigaction. Failing to do so is likely to cause the program to crash if the signal is received. Go programs routinely run with a limited stack, and therefore set up an alternate signal stack.

### PR DESCRIPTION
**Pull request by canepat**
This PR changes the implementation of `SignalHandler` to relying on `sigaction` system call on Linux and macOS platforms, so that we can use `SA_ONSTACK` flag on registered signal handlers.

Fixes #1940

### CODE REVIEW

File: silkworm/infra/concurrency/signal_handler.cpp [hunk 1]
```diff
@@ -106,12 +106,31 @@ std::atomic_int SignalHandler::sig_code_{0};
 std::atomic_bool SignalHandler::signalled_{false};
 std::function<void(int)> SignalHandler::custom_handler_;
 bool SignalHandler::silent_{false};
-std::map<int, void (*)(int)> previous_signal_handlers;
+
+using SignalHandlerFunc = void (*)(int);
+std::map<int, SignalHandlerFunc> previous_signal_handlers;
+
+static SignalHandlerFunc register_signal_action(const int signal_number, SignalHandlerFunc handler_func) {
```
Comment (JacekGlen) [inline silkworm/infra/concurrency/signal_handler.cpp:113]:
```suggestion
static SignalHandlerFunc register_signal_action(const int sig_code, SignalHandlerFunc handler_func) {
```
so it matches naming in the other parts of the class

**Review by JacekGlen — APPROVED** [review]
Tiny change only. Looks good!
