### PR TITLE
rpcdaemon: fix ots_getContractCreator

### LINKED ISSUE #2061: rpcdaemon: `ots_getContractCreator` always returns `null`
On my dev network, all invocations of `ots_getContractCreator` return `null` under Silkworm. When running Erigon without Silkworm it returns the hash and creator.

See https://github.com/otterscan/otterscan/blob/develop/docs/custom-jsonrpc.md#ots_getcontractcreator for reference.

### PR DESCRIPTION
**Pull request by lupin012**
Fixes #2061

### CODE REVIEW

File: silkworm/rpc/core/evm_executor.hpp [hunk 1]
```diff
@@ -47,7 +47,8 @@ enum PreCheckErrorCode {
     kInternalError,
     kIntrinsicGasTooLow,
     kMaxFeePerBlobGasTooLowError,
-    kTipHigherThanFeeCap
+    kTipHigherThanFeeCap,
+    kIsNotLondon
```
Comment (battlmonstr) [inline silkworm/rpc/core/evm_executor.hpp:51]: should this list be sorted?

**Review by battlmonstr — APPROVED** [review]
