### PR TITLE
infra: impl gRPC server global callbacks to check port conflicts

### LINKED ISSUE #1398: Improve the error message: Address already in use
When starting silkworm without arguments after staring erigon without arguments on the same computer, silkworm crashes with "Unrecoverable failure: Address already in use" and no other clues. Apparently it wants to occupy some default TCP/UDP ports that are in use by the erigon process.

The error message needs to be improved to explain what port is occupied, what for is it needed, and which command line parameter must be passed to customize it.

### PR DESCRIPTION
**Pull request by amitrahman1026**
Fixes #1398.

__________

### Previous clarifications:

```
Randomness seeded to: 2963361049
===============================================================================
All tests passed (2610918 assertions in 26 test cases)

Running silkworm/db/silkworm_db_test...
Filters: ~[ignore]
Randomness seeded to: 3955485080
===============================================================================
All tests passed (12989 assertions in 218 test cases)

CMake Error at cmake/run_unit_tests.cmake:45 (execute_process):
  execute_process failed command indexes:

    1: "Abnormal exit with child return code: Subprocess aborted"
```

Which don't really indicate any particular test causing this. Besides just not calling the `set_global_callback()` which seems to be the problematic case

After creating a proper singleton of `ServerGlobalCallbacks`, calling `set_global_callbacks()` like so

```
silkworm::rpc {
void set_global_callbacks() {
        grpc::Server::SetGlobalCallbacks(&ServerGlobalCallbacks::instance());
}
}  // namespace silkworm::rpc
```
seems to give a clue as to where it fails. Will start by looking into this part.

<details>

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
silkworm_db_test is a Catch2 v3.6.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
KvServer
  KvServer::shutdown OK: shutdown running server
-------------------------------------------------------------------------------
/Users/amit/Cpp_Projects/silkworm/silkworm/db/kv/grpc/server/kv_server_test.cpp:332
...............................................................................

/Users/amit/Cpp_Projects/silkworm/silkworm/db/kv/grpc/server/kv_server_test.cpp:332: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases:   99 |   98 passed | 1 failed
assertions: 4944 | 4943 passed | 1 failed

CMake Error at cmake/run_unit_tests.cmake:45 (execute_process):
  execute_process failed command indexes:

    1: "Abnormal exit with child return code: Subprocess aborted"

make: *** [run_unit_tests] Error 1
```
</details>

Although compiling with `-DCMAKE_CXX_FLAGS="-fsanitize=address"` Seems to lead me to somewhere different so I'm not too sure about this.

<details>

```sh
mainnet_genesis
-------------------------------------------------------------------------------
/Users/amit/Cpp_Projects/silkworm/silkworm/core/chain/genesis_test.cpp:65
...............................................................................

/Users/amit/Cpp_Projects/silkworm/silkworm/core/chain/genesis_test.cpp:65: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:  8 |  7 passed | 1 failed
assertions: 95 | 94 passed | 1 failed

AddressSanitizer:DEADLYSIGNAL
=================================================================
==18540==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010070c354 bp 0x00016fb245d0 sp 0x00016fb24590 T0)
==18540==The signal is caused by a READ memory access.
==18540==Hint: address points to the zero page.
    #0 0x10070c354 in absl::lts_20230125::container_internal::FindInfo absl::lts_20230125::container_internal::find_first_non_full<void>(absl::lts_20230125::container_internal::CommonFields const&, unsigned long)+0x14 (core_test:arm64+0x100434354)
    #1 0x1006191e8 in silkworm::InMemoryState::update_account(evmc::address const&, std::__1::optional<silkworm::Account>, std::__1::optional<silkworm::Account>)+0x2b0 (core_test:arm64+0x1003411e8)
    #2 0x100574d88 in silkworm::read_genesis_allocation(nlohmann::json_abi_v3_11_3::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, void> const&)+0x1160 (core_test:arm64+0x10029cd88)
    #3 0x1003415c4 in silkworm::CATCH2_INTERNAL_TEST_2()+0x25c (core_test:arm64+0x1000695c4)
    #4 0x1007daf64 in Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&)+0x154 (core_test:arm64+0x100502f64)
    #5 0x1007daa6c in Catch::RunContext::runTest(Catch::TestCaseHandle const&)+0x168 (core_test:arm64+0x100502a6c)
    #6 0x1007b9384 in Catch::Session::runInternal()+0x83c (core_test:arm64+0x1004e1384)
    #7 0x1007b8aec in Catch::Session::run()+0x3c (core_test:arm64+0x1004e0aec)
    #8 0x1007992d4 in main+0x50 (core_test:arm64+0x1004c12d4)
    #9 0x1991c20dc  (<unknown module>)

==18540==Register values:
 x[0] = 0x000000016fb25568   x[1] = 0x4f21b8da09fca0cd   x[2] = 0x0000000000000000   x[3] = 0x00000c7e0009a8b6  
 x[4] = 0x00006070003d45c0   x[5] = 0x0000000000000001   x[6] = 0x000000016eb28000   x[7] = 0x0000000000000001  
 x[8] = 0x00006070003d4570   x[9] = 0x0000407000114140  x[10] = 0x0000000000000000  x[11] = 0x0000000000000000  
x[12] = 0xffffffffffffffff  x[13] = 0x0000000000000000  x[14] = 0x00007fffffffffff  x[15] = 0x000010700001ffff  
x[16] = 0x000000010070c340  x[17] = 0x00000001014d85e0  x[18] = 0x0000000000000000  x[19] = 0x000000016fb25568  
x[20] = 0x4f21b8da09fca0cd  x[21] = 0x000000016fb25578  x[22] = 0x000000002df64ab2  x[23] = 0x0000007000020000  
x[24] = 0x000000002df64aad  x[25] = 0x000000002df64aaf  x[26] = 0x000000016fb25590  x[27] = 0x0000007000020000  
x[28] = 0x000000016fb24640     fp = 0x000000016fb245d0     lr = 0x000000010062979c     sp = 0x000000016fb24590  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (core_test:arm64+0x100434354) in absl::lts_20230125::container_internal::FindInfo absl::lts_20230125::container_internal::find_first_non_full<void>(absl::lts_20230125::container_internal::CommonFields const&, unsigned long)+0x14
==18540==ABORTING
CMake Error at cmake/run_unit_tests.cmake:45 (execute_process):
  execute_process failed command indexes:

    1: "Abnormal exit with child return code: Subprocess aborted"
```

</details>

### CODE REVIEW

**Comment by amitrahman1026** [comment]
@battlmonstr Thanks for the tips, this is definitely an interesting issue and I'm interested in exploring and seeing it through to completion :) I'll update on the findings and raise further questions once I have a better idea of the testing harness. 

I haven't had a chance to grok it with lldb yet, but I'll do so over the weekend. Are you open to keeping this bug open? I understand this is an introductory issue for newcomers that may have evolved a little. I ask because I have a few college exam coming up so this is going to be weekend hacking for me in terms of timeline. In the meantime if anyone else is interested to hop on alongside me please feel free as well.

**Comment by amitrahman1026** [comment]
@battlmonstr after poking around, managed to wrap this up. I also found out a few things.

Firstly, I'm not sure why `ci/circleci: linux-clang-16-release` is passing even with failing unit tests from my pervious iterations, might have to look into that.
image

Now to the meat of this issue with global callbacks with grpc.

The problem revolves around the lifetime of `grpc::Server::GlobalCallbacks`, it needs to be available to all instances of the `Server` class. 

With some gdb mashing and hints from https://github.com/grpc/grpc/issues/23204 and https://github.com/grpc/grpc/issues/37607, looks like this is a clean way to manage the lifetime of `grpc::Server::GlobalCallbacks` such that it remains available till all all instances of `Server` go out of scope.

```
class Server {
// ...
private:
    //! The global callbacks are shared between all instances of Servers
    inline static ServerGlobalCallbacks global_callbacks_{};
};
```

File: silkworm/infra/grpc/server/server.hpp [hunk 1]
```diff
@@ -174,6 +176,9 @@ class Server {
     //! The gRPC server instance tied to this Server lifetime.
     std::unique_ptr<grpc::Server> server_;
 
+    //! The global callbacks are shared between all instances of Servers
+    inline static ServerGlobalCallbacks global_callbacks_{};
```
Comment (battlmonstr) [inline silkworm/infra/grpc/server/server.hpp:180]:
```suggestion
    static inline ServerGlobalCallbacks global_callbacks_;
```

see https://github.com/erigontech/silkworm/blob/master/docs/code_style.md#p10-constants-definition-keywords

File: silkworm/infra/grpc/server/server_callbacks.hpp [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+    }
+
+  private:
+    class Callbacks final : public grpc::Server::GlobalCallbacks {
+      public:
+        Callbacks() = default;
+        ~Callbacks() override = default;
+
+        void PreSynchronousRequest([[maybe_unused]] grpc::ServerContext* context) override{};
+        void PostSynchronousRequest([[maybe_unused]] grpc::ServerContext* context) override{};
```
Comment (battlmonstr) [inline silkworm/infra/grpc/server/server_callbacks.hpp:45]:
```suggestion
        void PreSynchronousRequest(grpc::ServerContext*) override {};
        void PostSynchronousRequest(grpc::ServerContext*) override {};
```

File: silkworm/infra/grpc/server/server_callbacks.hpp [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+
+        void AddPort([[maybe_unused]] grpc::Server* server, const std::string& addr,
+                     [[maybe_unused]] grpc::ServerCredentials* creds, int port) override {
+            if (port != 0) {
+                SILK_TRACE << "Successfully bound server to address: " << addr << " on port: " << port;
+            } else {
+                SILK_ERROR << "Failed to bind server to address " << addr
+                           << ". Port is already in use.";
```
Comment (battlmonstr) [inline silkworm/infra/grpc/server/server_callbacks.hpp:53]: I suggest that here instead of logging we set an error flag (e.g. `ServerGlobalCallbacks::bad_port_error = true`), and then handle this flag here: https://github.com/erigontech/silkworm/blob/master/silkworm/infra/grpc/server/server.hpp#L84
by adjusting the `std::runtime_error` message for this case.

Ideally this flag should be stored per server (tied to each Server instance), but let's decide to not complicate the matters, and just use a single atomic_bool flag for all servers for now. Hopefully multiple server failures don't overlap.

After handling the error in server.hpp, the flag should be reset back to false.

This TRACE message could be removed now since you trace it here already:
https://github.com/erigontech/silkworm/blob/master/silkworm/infra/grpc/server/server.hpp#L81

**Review by battlmonstr — CHANGES_REQUESTED** [review]
Thanks for the effort :+1: See comments.

I will take care about the unit test succees on failures here: https://github.com/erigontech/silkworm/pull/2511

File: silkworm/infra/grpc/server/server_callbacks.hpp (hunk 3 above)
Comment (amitrahman1026) [reply silkworm/infra/grpc/server/server_callbacks.hpp]: That makes sense wrt to efficiency, thanks for the review! It does seem a little tough to keep. I would naively think of some server ID mapping to an error balck but unsure of the overhead/thread safety

File: silkworm/infra/grpc/server/server.hpp [hunk 4]
```diff
@@ -78,10 +80,17 @@ class Server {
...
 
         server_ = builder.BuildAndStart();
-        SILK_TRACE << "Server " << this << " bound at selected port: " << selected_port;
+
         if (server_ == nullptr) {
+            std::string error_msg = "cannot start gRPC server at " + settings_.address_uri;
+
+            if (ServerGlobalCallbacks::bad_port_error.load(std::memory_order_acquire)) {
+                error_msg += " (port already in use)";
+                ServerGlobalCallbacks::bad_port_error.store(false, std::memory_order_release);
```
Comment (battlmonstr) [inline silkworm/infra/grpc/server/server.hpp:89]:
```suggestion
            if (ServerGlobalCallbacks::bad_port_error) {
                error_msg += " (port already in use)";
                ServerGlobalCallbacks::bad_port_error = false;
```

nit: normally we only use explicit memory order if it matters for performance. Here it doesn't matter, so a default memory order is fine. In this case it is possible to use atomic_bool as a plain bool with a help of conversion and assignment operators that atomic_bool has.

An extra improvement idea is to have a method on ServerGlobalCallbacks to encapsulate read and reset of this flag.

**Review by battlmonstr — APPROVED** [review]
LGTM :+1:

File: silkworm/infra/grpc/server/server.hpp (hunk 4 above)
Comment (amitrahman1026) [reply silkworm/infra/grpc/server/server.hpp:89]: Gotcha, seems like a good spot for .exchange() then!

**Review by battlmonstr — APPROVED** [review]
perfect, thank you!
