### PR TITLE
infra: fix log timer lifecycle in execution pipeline

### LINKED ISSUE #2285: silkworm: crash after a restart following a successful first-cycle execution
Running Silkworm standalone in Release build on Linux Ubuntu 22.04 at commit 8944e21a276079b5c7bc8d335982e4c7a0557230 with:
```
silkworm --jwt /home/admin/prysm/jwt.hex --torrent.download.rate 512 --log.nocolor 2>&1
```

the crash happens after a restart following a successful first cycle of staged sync (i.e. historical block execution over snapshot files).

Crash details:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055b876989609 in void boost::asio::detail::deadline_timer_service<boost::asio::detail::chrono_time_traits<std::chrono::_V2::steady_clock, boost::asio::wait_traits<std::chrono::_V2::steady_clock> > >::async_wait<silkworm::Timer::launch()::{lambda(boost::system::error_code const&)#1}, boost::asio::any_io_executor>(boost::asio::detail::deadline_timer_service<boost::asio::detail::chrono_time_traits<std::chrono::_V2::steady_clock, boost::asio::wait_traits<std::chrono::_V2::steady_clock> > >::implementation_type&, silkworm::Timer::launch()::{lambda(boost::system::error_code const&)#1}&, boost::asio::any_io_executor const&) ()
[Current thread is 1 (Thread 0x7c4e70ffa640 (LWP 3406184))]
(gdb) where
#0  0x000055b876989609 in void boost::asio::detail::deadline_timer_service<boost::asio::detail::chrono_time_traits<std::chrono::_V2::steady_clock, boost::asio::wait_traits<std::chrono::_V2::steady_clock> > >::async_wait<silkworm::Timer::launch()::{lambda(boost::system::error_code const&)#1}, boost::asio::any_io_executor>(boost::asio::detail::deadline_timer_service<boost::asio::detail::chrono_time_traits<std::chrono::_V2::steady_clock, boost::asio::wait_traits<std::chrono::_V2::steady_clock> > >::implementation_type&, silkworm::Timer::launch()::{lambda(boost::system::error_code const&)#1}&, boost::asio::any_io_executor const&) ()
#1  0x000055b876989851 in silkworm::Timer::launch()::{lambda(boost::system::error_code const&)#1}::operator()(boost::system::error_code const&) const ()
#2  0x000055b876989c6d in boost::asio::detail::wait_handler<silkworm::Timer::launch()::{lambda(boost::system::error_code const&)#1}, boost::asio::any_io_executor>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
#3  0x000055b8768e1dfc in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#4  0x000055b876964698 in silkworm::node::NodeImpl::start_execution_log_timer()::{lambda()#1}::operator()() const ()
#5  0x000055b8781dc50f in silkworm::concurrency::async_thread(std::function<void ()>, std::function<void ()>, char const*, std::optional<unsigned long>)::{lambda()#1}::operator()() const ()
#6  0x000055b87841f41b in thread_proxy ()
#7  0x00007fccef246ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007fccef2d8850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

```

### PR DESCRIPTION
**Pull request by canepat**
Fixes #2285 by removing `LogTimer` class and refactoring `Timer` class so that:

1. we pass self pointer to timer completion handler lambda as `std::shared_ptr` to avoid use-after-free
2. we now handle `boost::asio::error::operation_aborted` error code (i.e. timer gets cancelled before expiration) by exiting

In order to avoid the dreaded `bad_weak_ptr` exception when using `std::enable_shared_from_this` to implement the solution 1., I've forced usage of static factory method `create` as the only way to instantiate a `Timer` object and then start it (you cannot start it into the constructor anymore).
Moreover, I've removed `LogTimer` class in favour of a private method of `ExecutionPipeline` as timer callback not to duplicate the factory method.

*Extras*
- fix one runtime error in `ClientContextPool` destructor found by ASAN on macOS executing `silkworm_capi_test`

### CODE REVIEW

File: silkworm/infra/common/timer_test.cpp [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+
+namespace silkworm {
+
+TEST_CASE("Timer lifecycle race condition") {
+    struct TimerInfo {
+        std::string description;
+        uint32_t interval;
+    };
+    const std::vector<TimerInfo> timer_infos{
+        {"long_running_timer", 10'000},
```
Comment (battlmonstr) [inline silkworm/infra/common/timer_test.cpp:33]: Is this gonna wait for 10 sec? If yes, I'd like to avoid this. Perhaps removing this line is good enough?

**Review by battlmonstr — APPROVED** [review]

File: silkworm/infra/common/timer_test.cpp (hunk 1 above)
Comment (canepat) [reply silkworm/infra/common/timer_test.cpp]: > Is this gonna wait for 10 sec? If yes, I'd like to avoid this. Perhaps removing this line is good enough?

It wasn't waiting for 10 sec because it didn't expired. In any case, I've improved the unit tests and also reduced the timer durations, so it's not an issue anymore.
